#!/usr/bin/env bash
KAFKA_PID=0

# Set up the configuration.
/opt/kafka/kafka-config $@

term_handler() {
  echo 'Stopping Kafka....'
  if [ $KAFKA_PID -ne 0 ]; then
    kill -s TERM "$KAFKA_PID"
    wait "$KAFKA_PID"
  fi
  echo 'Kafka stopped.'
  exit
}

# Capture kill requests to stop properly
trap "term_handler" SIGHUP SIGINT SIGTERM
/opt/kafka/bin/kafka-server-start.sh /opt/kafka/server.properties &
KAFKA_PID=$!

wait
